# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Release
        env: 
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: npx semantic-release
